name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" # Exécution tous les jours à minuit
  workflow_dispatch: # Permet l'exécution manuelle
  push:
    branches:
      - main


permissions:
  contents: write
  pull-requests: write # Permission pour créer et merger des PRs


jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: |
          cd portfolio
          npm install

      - name: Update WakaTime stats
        env:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        run: |
          cd portfolio
          npx tsx services/update-wakatime.ts

      - name: Create Pull Request
        run: |
          # Configurer Git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Créer une nouvelle branche avec un timestamp
          current_date=$(date +%Y%m%d_%H%M%S)
          branch_name="update-wakatime-stats-${current_date}"
          git checkout -b $branch_name

          # Ajouter et commit les changements
          git add portfolio/public/wakatime-stats.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update WakaTime stats" && git push origin $branch_name)

          # Créer et merger la PR automatiquement si il y a des changements
          if [ $? -eq 0 ]; then
            gh pr create \
              --title "Update WakaTime stats - ${current_date}" \
              --body "Mise à jour automatique des statistiques WakaTime" \
              --base main \
              --head $branch_name
            
            # Attendre quelques secondes pour s'assurer que la PR est créée
            sleep 5
            
            # Merger la PR automatiquement
            gh pr merge --auto --merge --delete-branch "${GITHUB_REPOSITORY}#$(gh pr list --head $branch_name --json number -q '.[0].number')"
          fi

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
